#!/usr/bin/python3

from lib.client import download_file
from lib.utils import parse_download_file   
import logging

if __name__ == "__main__":
    
    args = parse_download_file()
    logging.basicConfig(level=args.verbose)
    logger = logging.getLogger(__name__)

    logger.info('Starting File Transfer App with TCP')
    download_file(args.dst, args.filename, args.port, logger)
    logger.info('File transfer complete')

    