#!/usr/bin/python3
import logging
import traceback

from lib.server import TCPServer, UDPServer
from lib.utils import parse_server_start, Protocol

if __name__ == "__main__":
    args = parse_server_start()
    logging.basicConfig(level=args.verbose, format='%(asctime)s - [%(levelname)s] - %(message)s', datefmt='%Y/%m/%d %H:%M:%S')
    logger = logging.getLogger(__name__)
    
    if args.protocol == Protocol.TCP:
        server = TCPServer('localhost', args.port, args.dest, logger)
        logger.info('Starting TCP server...')
    elif args.protocol == Protocol.UDP:
        server = UDPServer('localhost', args.port, args.dest, logger)
        logger.info('Starting UDP server...')

    try:
        server.start_server()
    except:
        logger.info('Stopping server...')
        server.stop_server()
        traceback.print_exc()

