#!/usr/bin/python3

from lib.client import transfer_file
from lib.utils import parse_upload_file   
import logging
import os

if __name__ == "__main__":
    
    args = parse_upload_file()
    logging.basicConfig(level=args.verbose)
    logger = logging.getLogger(__name__)

    logger.info('Starting File Transfer App with TCP')
    transfer_file(args.src, args.filename, args.port, logger)
    logger.info('File transfer complete')

