#!/usr/bin/python3

from lib.tcpclient import TCPClient
from lib.udpclient import UDPClient
from lib.utils import parse_upload_file, Protocol
import logging
import os

if __name__ == "__main__":

    args = parse_upload_file()
    logging.basicConfig(
        level=args.verbose,
        format="%(asctime)s - [upload %(levelname)s] - %(message)s",
        datefmt="%Y/%m/%d %H:%M:%S",
    )
    logger = logging.getLogger(__name__)

    if args.protocol == Protocol.TCP:
        client = TCPClient(args.port, args.filename, logger)
        logger.info("Starting File Transfer App with TCP...")
    elif args.protocol == Protocol.UDP:
        client = UDPClient(args.port, args.filename, logger)
        logger.info("Starting File Transfer App with UDP...")

    client.transfer_file(args.src)
    logger.info("File transfer complete")
